### ISSUE TITLE
RabbitMQ Transport

### ISSUE THREAD

**Issue by ShaneCourtrille** [JasperFx/jasper#120]
Are there any plans on supporting Azure Service Bus as a transport?

**Comment by jeremydmiller** [comment]
@ShaneCourtrille Hey man, it's been awhile. I think we'll be able to get at what's effectively an AMPQ transport for Jasper before too long with RabbitMQ in mind. In theory, that should buy us Azure Service Bus for free. Wouldn't count until someone proves that it works.

Would you be interested in that?

**Comment by jeremydmiller** [comment]
cc // @mike-schenk

At work we're going to need a persistent queueing mechanism that doesn't depend on having permanent, local storage. To that end, it's time to get some support for a robust, enterprise-y queue like RabbitMQ.

In theory, this should be:

* A new project that's an addon to Jasper (`Jasper.AMPQ`?)
* A new implementation of `ITransport` and `ICallback` -- and out assumption all along has been that these abstractions weren't "locked down" until this story is done
* Thinking that the Uri's for these endpoints would be something like "ampq://[machine name]:[port]/[queue name]"

**Comment by ShaneCourtrille** [comment]
Just realized I never clicked the Comment button on my response.

Based off what I've been able to learn that seems like it should work nicely.

**Comment by jeremydmiller** [comment]
@mike-schenk, here's finally a braindump on this thing:

* You'll need to implement the `ITransport` and `IMessagingCallback` interfaces. I've got a couple issues up for tomorrow morning that should prune and simplify the callback at least #188 & #189.
* The RabbitMQ model is different than the LQ based transports we've used before. I *think* that we should still publish Jasper's subscriptions model even though RabbitMQ does most of the routing for you. It's still useful to use the published subscriptions to establish message versions and capabilities. What we *should* do differently though is have some easy utility to use the subscriptions to automatically create the RabbitMQ bindings per message type.
* For the `reply-uri` header values, all that is used for is the request/reply mechanics. In the ampq transport, I vote that we use the built in control channel for the app that should be a "jasper" transport that every jasper app will support, and let that be the local callback Uri for replies.
* If you want, look for the `IJasperExtension` and `JasperModuleAttribute` usage if you wanna make this be just a drop in extension.

**Comment by jeremydmiller** [comment]
Oh, and maybe look at the `message-type` header that's derived from the message type to help create the RabbitMQ bindings on a per message basis? That's about what MassTransit does.

**Comment by jeremydmiller** [comment]
Renaming this to RabbitMQ, w/ a separate issue later for Azure Service Bus

**Comment by jeremydmiller** [comment]
Working through this just fine, but here's a running list of optimizations and tweaks for later after it all works w/ end to end tests:

- [ ] Change `IEnvelopeMapper` to avoid needing the `BasicDeliverEventArgs` object
- [ ] New `IReceiverCallback.Received(Uri, Envelope)` signature for a single envelope

**Comment by jeremydmiller** [comment]
Basics are done, time for the refactorings above

**Comment by jeremydmiller** [comment]
I'm declaring victory on this one. Wasn't a huge amount of code. Should provide a decent pattern for Azure Service Bus next. Kafka support looks super weird though.
