### ISSUE TITLE
Handle the case of multiple subscriptions to the same destination w/ different content-type's

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#168]
ONLY USE ONE OF THEM.

If one isn't application/json, use that?

**Comment by ShaneCourtrille** [comment]
Is there going to be a way to validate your configuration ala StructureMap?

**Comment by jeremydmiller** [comment]
I've got something cooking that would be similar for subscriptions, but in this case it's a valid configuration, but needs to not double send the message.
