### ISSUE TITLE
Hard-coded IP address for listening

### ISSUE THREAD

**Issue by mike-schenk** [JasperFx/jasper#234]
ListeningAgent constructor creates TcpListener with a hardcoded IPEndPoint address of IPAddress.Loopback.Is that a mistake?

Should it be IPAddress.Any? IPAddress.IPv6Any?
Should it be passed in as a parameter and come from settings?

Should it be possible to listen on both IPv4 and IPv6 addresses at the same time?

**Comment by jeremydmiller** [comment]
Yes to all. You might peek at the SocketConnection class in Storyteller 'cause that's gotten a lot of recent pull requests for IPv6 usage.
