### ISSUE TITLE
Semantically different Publish() method

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#268]
Slightly different from Send() just from the standpoint that it would not throw any exceptions if no routes were found. Would still call it locally too

**Comment by jeremydmiller** [comment]
This is done in the "restructure" branch. Will be pulled in in the next day or two

**Comment by mike-schenk** [comment]
The changes relative to having a ServiceBus instance enlist in a "transaction" look pretty good.

I don't think all of the new things should be exposed through the IServiceBus interface though. If I'm a regular external consumer of the IServiceBus interface, I shouldn't be calling FlushOutstanding(), or accessing the Outstanding or Persistence properties.

I like that using this mechanism doesn't require changing from using IServiceBus to using something like IOutbox. I like the simple IEnvelopePersistor interface too.

One potential problem I see in the code as-written though: it looks like it could cause SendAndWait<T> to deadlock.

**Comment by jeremydmiller** [comment]
@mike-schenk Sounds like you're good with this approach, so I'll start fleshing out a lot more tests on it. Good call on the SendAndWait. I'll have that opt out of the persistence in all of those cases.

I wanna kick the can down the road just a bit on whether or not we hide those additional members on IServiceBus just until we do the Sql Server backed version of this, but I agree with you on that one. It's just that those things would have to be exposed to any kind of transactional strategy. We *could* expose them all off of a `IServiceBus.EnlistedTransaction` property or something like that.
