### ISSUE TITLE
Introduce message type "ownership" for commands versus events

### ISSUE THREAD

**Issue by mike-schenk** [JasperFx/jasper#275]
If a service handles a command, it is the owner of that message type. If it publishes an event, it is the owner of the event message type.

**Comment by jeremydmiller** [comment]
Tasking:

- [ ] JasperRegistry.Subscribe.AsOwnerTo<T>()
- [ ] JasperRegistry.Subscribe.AsOwnerTo(Type)
- [ ] JasperRegistry.Subscribe.AsOwnerTo(Func<T, bool>)
- [ ] SubscriptionRequirement.Owner : bool
- [ ] Gets compiled into ServiceCapabilities
- [ ] MessagingGraph.MultipleOwners, and fails the SubscriptionCommand

**Comment by jeremydmiller** [comment]
I don't think this is ever going to get done
