### ISSUE TITLE
Integrating with barebones ASP.NET Core app

### ISSUE THREAD

**Issue by pekkah** [JasperFx/jasper#300]
Trying to get barebones ASP.NET core app to rung with Jasper but after calling `UseJasper` I'm getting an exception. Note that my registry class is empty.

```
"System.UriFormatException: Invalid URI: The hostname could not be parsed.\n   at 
System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)\n   at System.Uri..ctor(String 
uriString)\n   at Jasper.Util.StringExtensions.ToUri(String uriString)\n   at 
System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()\n   at 
System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)\n
   at Jasper.Http.Transport.HttpTransport.StartListening(BusSettings settings)\n   at 
Jasper.Bus.Transports.ChannelGraph.Start(BusSettings settings, ITransport[] transports, UriAliasLookup 
lookups, CapabilityGraph capabilities, CompositeMessageLogger logger)\n   at 
Jasper.Bus.ServiceBusActivator.<Activate>d__10.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Jasper.JasperRuntime.<bootstrap>d__30.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Jasper.JasperRuntime.For(JasperRegistry registry)\n   at Jasper.Http.JasperWebHostBuilderExtensions.UseJasper(IWebHostBuilder builder, JasperRegistry registry)
```

**Comment by pekkah** [comment]
Nothing special in there

```
WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
		.UseJasper<MyApp>()
                .Build();
```

**Comment by pekkah** [comment]
I'm not doing anything in the constructor of `MyApp`.

**Comment by pekkah** [comment]
If I use a simple console app with the same registry it runs without error, but if I try to enable http transport with copy paste code from the documentation it throws that same error.

**Comment by jeremydmiller** [comment]
@pekkah The reason I'm asking is that it's choking on the format of the url it's reading from the ASP.net Core configuration. I've never tested Jasper with anything but `UseUrls("http://localhost:PORT"). Jasper does a naive check through the settings to grab the port number -- and yes, that definitely needs to get smarter about how it parses.

**Comment by jeremydmiller** [comment]
@pekkah Hey, any chance I could see your call to `UseUrls()` in your application setup?

**Comment by pekkah** [comment]
Sorry for not replying earlier. Will test again when these changes make to the nuget.

**Comment by jeremydmiller** [comment]
@pekkah No worries. Unless you feel like trying out master, wanna wait until I get 0.6 up on Nuget?

What I've done is making it smarter about how it parses the uri strings for the case of "http://*:5000" type wildcards, and I have it using the aspnet code itself for looking up the server addresses on `IServer`, so it should pick up anything it reads from configuration or the magic environment variables it does under the covers.
