### ISSUE TITLE
async handlers

### ISSUE THREAD

**Issue by francisco-ltech** [JasperFx/jasper#302]
Hi,

Is additional configuration required for an async Handle() definition?

This works (is triggered): public void Handle()
This doesn't work: public async Task Handle()

Thanks,

**Comment by jeremydmiller** [comment]
No, and there are tests for that in the codebase if you look. What do you mean it "doesn't work"?

**Comment by francisco-ltech** [comment]
My bad sorry, my dependency injection was wrong and it wasn't instantiating the handler.
