### ISSUE TITLE
Exponential Backoff error handling

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#364]
Per conversation with @MedAnd today on Gitter.

https://en.wikipedia.org/wiki/Exponential_backoff

Shouldn't be very hard. Might just be an example in the documentation showing how to build a custom error handler policy to do that.

**Comment by MedAnd** [comment]
Been using Polly for a while now and would be good to allow some level of support for 3rd party libraries such as these...

**Comment by jeremydmiller** [comment]
@MedAnd Cheating sorta and just having Jasper use Polly for this w/ some Jasper centric helpers
