### ISSUE TITLE
asp.net mvc endpoints give 404 when using jasper

### ISSUE THREAD

**Issue by paulvanbladel** [JasperFx/jasper#378]
Using jasper inside makes that mvc endpoints are not reachable.

Simplest way to reproduce is to start sample OutboxInMVCWithMarten

Cheers
paul.

**Comment by jeremydmiller** [comment]
Seems like an important detail to address;)

**Comment by paulvanbladel** [comment]
Unless i am doing something incredibly stupid.😀

**Comment by jeremydmiller** [comment]
You can work around it by having the UseJasper() call absolutely last in your WebHostBuilder setup, but this still needs to get fixed.

**Comment by paulvanbladel** [comment]
Isn't it like that in the outbox sample?
 public static IWebHost BuildWebHost(string[] args)
        {
            return WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseJasper<OutboxSampleApp>()
                .Build();
        }
    }

**Comment by paulvanbladel** [comment]
```
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore().AddJsonFormatters();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseMvc();
        }
    }
```

**Comment by paulvanbladel** [comment]
Under the assumption that 
1. adding Jasper on an out of the box web api with values controller keeps the existing api endpoints working;
2. an empty JaspRegistry (only a serviceName) is allowed;
3. jasper works fine with dotnet core 2.0;

following repo should also work but it isn't working on my windows machine, on another windows machine nor on linux :)

git@github.com:paulvanbladel/JasperIssue.git

When you comment out .UseJasper<ServiceBusApp>() the api will work though.
Feel free to give it a try.

**Comment by jeremydmiller** [comment]
@paulvanbladel Gotcha.  I double checked, and Jasper's tests for ASP.Net Core integration are all passing, **but** they aren't testing with MVC added in as well. It's easily possible that something w/ the newish bootstrapping in Jasper defeats the controller discovery or something like that in MVC Core. I'll do some testing early next week with the MVC + Jasper combo. I'll need it fixed for something at work anyway;-)

**Comment by paulvanbladel** [comment]
Thanks. For me nothing urgent. I am currently just exploring marten and jasper and i like it.

**Comment by jeremydmiller** [comment]
@paulvanbladel I'm not *quite* done with this, but I'm zooming in on the last problem. I have some unkind thoughts about MVC's bootstrapping code right now though.

**Comment by paulvanbladel** [comment]
@jeremydmiller 
You make me curious :)

**Comment by jeremydmiller** [comment]
@paulvanbladel That was unpleasant. Was pretty well exactly what I thought it was going to be, but took a bit of spelunking to figure out how to pass the missing assembly name data to MVC to make it all work. I did quite a bit of customization to the ASP.Net bootstrapping within Jasper itself to try to parallelize the loading, and some of that work broke MVC because it assumes that certain services are available in the `ServiceCollection` being passed around at bootstrapping time.

This will be in Jasper v0.8 hopefully this afternoon.
