### ISSUE TITLE
is there a Lightweight service bus sample?

### ISSUE THREAD

**Issue by paulvanbladel** [JasperFx/jasper#395]
Jeremy,
I saw there there is a nuget package called JasperBus
https://www.nuget.org/packages/JasperBus/0.2.1-alpha-88
I'm looking for a light-weigth service bus for simple integration events between microservices.
What's your recommendation? Any sample available?
thx

**Comment by jeremydmiller** [comment]
That is what "Jasper" itself is trying to be. We started with "Jasper" + "JasperBus" + "JasperHttp", folded everything into just "Jasper" so it was easier to manage.

**Comment by jeremydmiller** [comment]
Ah, sorry, didn't read the question well enough. Thought I'd try to write up some tutorials next week. How about a "ping/pong"? Kinda hello world for service bus, and there's already that sample in the codebase.

**Comment by paulvanbladel** [comment]
Well indeed, maybe a dedicated github repo with some samples would be great for giving more exposure to your brilliant work.
The current samples might miss a bit coherence. I think that samples that start with the real easy scenarios and are just F5-able solutions are the best you can get when learning a new Lib/framework.
I'm very willing to contribute but will patiently wait for your first basic sample :)
The Ping/pong might be ok, but I associate that more with request response style rather than pub/sub.

**Comment by jeremydmiller** [comment]
@paulvanbladel Do you have any suggestions or idea for what that tutorial would look like? I'm finally at a place where I could mess with that

**Comment by paulvanbladel** [comment]
Good question...
Probably things in the order management area appeal to most people knowledge domain.

**Comment by jeremydmiller** [comment]
Look at this:  http://jasperfx.github.io/documentation/tutorials/lightweight_bus/

**Comment by jeremydmiller** [comment]
@paulvanbladel Only took most of a year to get around to this!

**Comment by paulvanbladel** [comment]
@jeremydmiller yeah, I understand, it's open source work. Anyhow, the tutorial looks great. Thanks a lot.
