### ISSUE TITLE
Cannot build Jasper from VS2017 15.7

### ISSUE THREAD

**Issue by ShaneCourtrille** [JasperFx/jasper#417]
When I try to build I receive this error:

NU1605	Detected package downgrade: Microsoft.NETCore.App from 2.0.5 to 2.0.0. Reference the package directly from the project to select a different version. 
 Jasper.Marten.Tests -> Jasper.Testing -> Microsoft.NETCore.App (>= 2.0.5) 
 Jasper.Marten.Tests -> Microsoft.NETCore.App (>= 2.0.0)	Jasper.Marten.Tests	C:\data\GitHub\jasper\src\Jasper.Marten.Tests\Jasper.Marten.Tests.csproj	1	

The problem is caused by the fact that the following line exists in Jasper.Testing.csproj but not in the other test projects.  Fixed it by adding it in the <PropertyGroup> at the top of the DurabilitySpecs.csproj, Jasper.Marten.Tests.csproj, Jasper.RabbitMQ.Testing.csproj.

`   <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>`

I can PR a fix or you can just fix yourself as it's 2 seconds.

**Comment by florimm** [comment]
I created PR for this issue.

**Comment by jeremydmiller** [comment]
This is fixed by the PR from @florimm
