### ISSUE TITLE
CS0103: The name '_messagingRoot' does not exist in the current context

### ISSUE THREAD

**Issue by paulvanbladel** [JasperFx/jasper#422]
I'm trying to run the basic pinger and ponger sample.
It works great when running directly from the source (this this github repo), but when I use nuget packages instead, I get
CS0103: The name '_messagingRoot' does not exist in the current context
If more handy for you to reproduce, I'm happy to provide a small sample reproducing the problem.

**Comment by paulvanbladel** [comment]
No, this repo works fine it's with the very last nuget of jasper.commandline.  I think it's 0.8.1
No worries about the tutorials :)

**Comment by paulvanbladel** [comment]
is there a workaround I can apply?

**Comment by jeremydmiller** [comment]
The problem if there is one would be in Jasper. Can you force it to use the very latest Jasper instead of relying on what Jasper.CommandLine brings down?

And apropos of that, what would you think about just rolling the Jasper.CommandLine stuff into Jasper itself? Avoid this potential problem in the long run? Simpler maintenance on my end too.

**Comment by paulvanbladel** [comment]
Yeah indeed, I use Jasper.CommandLine and not directly Jasper. I'll try that.
Well, ... I don't know, probably the same "separation" rules would apply for nuget packages as there are for plain dlls, npm packages, ...
Just thinking loudly, could something inside the build process detect that a change in a nuget package impacts "upstream" nuget packages?
Anyhow, if the functionality of Jasper.CommandLine is very closely related to Jasper, I wouldn't just think too much and integrate them :)
Cheers

**Comment by jeremydmiller** [comment]
It's just too hard to keep things up separately, and the Nuget resolution rules now in SDK projects would let this thing happen again. I'm going to combine them tonight. Makes everything easier to manage anyway.

**Comment by jeremydmiller** [comment]
@paulvanbladel ,

I'm closing this one w/ the claim that it's fixed by the latest Lamar. I'm trying to squeeze out a little 0.9.0 release soon, but I need to switch to Marten for awhile after this.
