### ISSUE TITLE
Rip out Request/Reply Features

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#425]
@izep Do you guys care about this at all? The main reason it was there in the first place is for backward compatibility w/ fubu usage for you guys.

* It's extra complexity in the internals
* The tests for it are slow
* You'd use HTTP services more easily anyway for what it does

**Comment by jeremydmiller** [comment]
@JordanZaerr Sounds like you'd be the one to care. If we did this, you'd have to move to HTTP services in the places where you're using request/reply or send and await w/ fubu today.

**Comment by JordanZaerr** [comment]
I'm only aware of one project that uses the actual `Request<>()` method.  If that also extends to the `RespondToSender` stuff then there are more things using that.

**Comment by jeremydmiller** [comment]
RespondToSender just sends a message back to the original sender. Doesn't really use the same mechanics. How about SendAndAwait()?

**Comment by JordanZaerr** [comment]
I searched our internal github and didn't find anything for `SendAndAwait` other than a commit that removed it.   I'm going to say its probably fine to remove and we'll figure something out for the app using `Request<>`.

**Comment by jeremydmiller** [comment]
Meh, it's more work to remove it than it's worth. It can stay. Nothing to see here, move along...


@JordanZaerr You'd be better off using HTTP services anyway instead of the hokey Request/Reply mechanics. The "global" option is usable though.
