### ISSUE TITLE
Refactor [MartenTransaction] and [SqlTransaction] into a more generic [Transaction] so that at run-time this can be defined

### ISSUE THREAD

**Issue by MedAnd** [JasperFx/jasper#431]
Currently [MartenTransaction] and [SqlTransaction] are wired into the code directly... consider refactoring into a common [Transaction] so that at run-time (in the bootstrapping logic?) one can pick Marten, MS Sql, Azure Event Hubs, Azure Service Bus etc. 

Above should allow solutions built with Jasper to change messaging & storage platforms with minimal modification.

PS. Not sure if duplicate of https://github.com/JasperFx/jasper/issues/369

**Comment by jeremydmiller** [comment]
@MedAnd I'm gonna play with this one this weekend with an eye toward simplifying the load testing harnesses
