### ISSUE TITLE
Publishing rules for ClientMessage and bring back WebSockets transport

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#441]
This is definitely a **Low** priority as it might be better to just have a SignalR transport. The WebSockets projects have been removed from the solution. See if we wanna bring them back

**Comment by joshua1** [comment]
would be nice to have signalr for frontend realtime interaction

**Comment by jeremydmiller** [comment]
And I'm closing this because it's more likely that we'd just use SignalR and not support anything custom. Might be cool to use a SignalR transport someday.
