### ISSUE TITLE
Exceptions thrown in startup tasks are being swallowed

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#486]
Kind of a big deal, but the "no duplicate route" exception gets swallowed, and other exceptions in teh MessagingActivator are getting swallowed. Kind of a huge, massive problem

**Comment by jeremydmiller** [comment]
ASP.Net Core swallows exceptions thrown by IHostedService.StartAsync(). We need to think about this one.

**Comment by jeremydmiller** [comment]
Also collect exceptions in all the sending and listening agents too. Maybe deal w/ this in the `Run()` methods in the command line tooling

**Comment by cwe1ss** [comment]
Fyi, this behavior will probably change in ASP.NET Core 3: 
https://github.com/aspnet/AspNetCore/issues/5900
