### ISSUE TITLE
StructureMap with JasperFX

### ISSUE THREAD

**Issue by chsami** [JasperFx/jasper#506]
Hi,

Can Structuremap no longer be used with JasperFx and are we forced to use Lamar?

JasperFx version: 0.9.8.6
Structuremap: 4.7.0
Structuremap.AspNetCore: 2.0.0

I created the most simple solution to test jasperFx with structuremap. Here is the code 

my program class:

```
public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStructureMap()
                .UseJasper()
                .UseStartup<Startup>();
```

I keep getting the following error when at runtime

> instance 'Object:  new NulloMetrics()' with ReturnType ConstructorInstance<NulloMetrics> cannot be cast to Jasper.Messaging.Logging.IMetrics

stacktrace:

>    at StructureMap.Graph.PluginFamily.assertInstanceIsValidForThisPluginType(Instance instance)
>    at StructureMap.Graph.PluginFamily.AddInstance(Instance instance)
>    at StructureMap.Graph.PluginFamily.SetDefault(Instance instance)
>    at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
>    at StructureMap.Registry.Configure(PluginGraph graph)
>    at StructureMap.PluginGraphBuilder.RunConfigurations()
>    at StructureMap.PluginGraphBuilder.Build()
>    at StructureMap.Container..ctor(Registry registry)
>    at StructureMap.StructureMapServiceProviderFactory.CreateServiceProvider(Registry registry)
>    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Send.Program.Main(String[] args) in C:\Users\Consultant\Downloads\Send\Send\Program.cs:line 19

**Comment by jeremydmiller** [comment]
Well, first off, thank you for trying out Jasper at all!

But, Jasper is purposely designed to only work with [Lamar](https://jasperfx.github.io/lamar) as its IoC container and will not function with anything else. That is documented, but we could definitely do something better in the startup to tell you "sorry, you have to use Lamar"

You don't have to do anything to opt into Lamar other than the call to `UseJasper()`.

**Comment by chsami** [comment]
> Well, first off, thank you for trying out Jasper at all!
> 
> But, Jasper is purposely designed to only work with [Lamar](https://jasperfx.github.io/lamar) as its IoC container and will not function with anything else. That is documented, but we could definitely do something better in the startup to tell you "sorry, you have to use Lamar"
> 
> You don't have to do anything to opt into Lamar other than the call to `UseJasper()`.

Alright, good to know! Thanks for the quick reply !
