### ISSUE TITLE
No way to allow handler discovery to scan an entire assembly

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#523]
The `HandlerSource` provided by `IHandlerConfiguration.Discovery()`  provides methods to add individual types, or types that implement a specific interface or convention, but no method to allow scanning an entire assembly or set of assemblies.  Something like the following would be helpful:

```
Handlers.Discovery(_ => {
   _.IncludeAssembly(myAssembly);
   _.IncludeAssemblies(myArrayOfAssemblies);
});
```

**Comment by jeremydmiller** [comment]
Fixed by #523. Should add docs, but later.
