### ISSUE TITLE
Scheduled messages processed immediately when routed to local queue

### ISSUE THREAD

**Issue by lovmoen** [JasperFx/jasper#528]
When calling IMessageContext.SheduleSend<T>() with a message which is subsequently routed to a local queue, the message is processed immediately.

**Comment by lovmoen** [comment]
This seems to be related to the durability status of the queue; if it is a non-durable queue, ScheduleSend() works as expected, whereas a durable queue will execute the handler immediately. In both cases, Schedule() does not invoke the handler at all.
See https://github.com/lovmoen/myjaspertest/tree/schedule-durable-queue and https://github.com/lovmoen/myjaspertest/tree/schedule-durable-queue for demonstrations of the aforementioned behaviour.

**Comment by jeremydmiller** [comment]
I'm finally looking at this today.

**Comment by jeremydmiller** [comment]
@lovmoen `ScheduleSend` is all working in master as it's supposed to. I tried it with both durable and non-durable loopback queues.  I tried `Schedule()` too, and it works. 

That was doing the setup by using `Publish.AllMessagesTo("loopback://durable/something")`.

It's possible that the screw up you're seeing is from other configuration alternatives. And it certainly wouldn't hurt to tighten up the configuration options.

**Comment by jeremydmiller** [comment]
Serious egg on my face. Fixed by https://github.com/JasperFx/jasper/pull/532

**Comment by jeremydmiller** [comment]
I'm reopening this. Not sure what's going on, but see https://github.com/lovmoen/myjaspertest/tree/schedule-durable-queue. Add tests to lock it down whatever it is.

**Comment by jeremydmiller** [comment]
@lovmoen I tried this again today in master, with both `Schedule()` and `ScheduleSend()`, and again with both Sql Server & Postgresql backed message persistence and finally w/ no persistence. In all cases, the code behaved as expected. I'm closing this.
