### ISSUE TITLE
Jasper 0.9.14 throws MissingMethodException with Marten 3.8

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#538]
When using the latest Jasper and Jasper.Persistence.Marten along with Marten 3.8 I get the following:

> System.MissingMethodException
HResult=0x80131513
Message=Method not found: 'DocumentMappingExpression1<!0> DocumentMappingExpression1.Duplicate(System.Linq.Expressions.Expression1<System.Func2<!0,System.Object>>, System.String, System.Nullable1<NpgsqlTypes.NpgsqlDbType>, System.Action1<Marten.Schema.IndexDefinition>)'.
Source=Jasper.Persistence.Marten
StackTrace:
at Jasper.Persistence.Marten.MartenBackedPersistence.<>c.<Configure>b__0_0(StoreOptions options)
at Jasper.Settings.SettingsBuilder`1.Build(WebHostBuilderContext context)

with:
>Exception thrown: 'System.MissingMethodException' in Jasper.dll
Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.OperationCanceledException' in System.Private.CoreLib.dll

**Comment by CodingGorilla** [comment]
Moving this from gitter conversation so there's a record of the issue.

**Comment by jeremydmiller** [comment]
This is fixed in 0.9.15
