### ISSUE TITLE
Remove generic class constraint on ICommandBus.Invoke

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/jasper#579]
Currently the `ICommandBus.Invoke<T>()` method has a generic constraint requiring `T` to be a class.  This seems to be only to help simplify the casting of the return value as the method's return is:
```c#
   return result as T;
```

This limits the usefulness as, for performance reasons, many return values are `struct` results.

**Comment by jeremydmiller** [comment]
Just like you said, was only because of the casting mechanics. I'm getting this right now.

**Comment by jeremydmiller** [comment]
I don't know that the struct is gonna buy you much because I think it's still gonna get boxed by Jasper carrying it around as an `object` in its internals

**Comment by CodingGorilla** [comment]
Yea, for my purposes anyways, I take advantage of the `struct` in my code when possible, but the conventions that imposes require me to pass the same result through Jasper when I use it as a mediator, so I expect I will lose some of the benefits in that case.  But it keeps my conventions intact.

**Comment by jeremydmiller** [comment]
@CodingGorilla Is your input command a struct as well? That's a problem too

**Comment by CodingGorilla** [comment]
No, they are classes.  I'm trying to think if you could ever benefit from making the commands structs, and as you say, they're almost certainly going to get boxed so I can't imagine it would be useful.  But would removing the constraint be difficult?

**Comment by jeremydmiller** [comment]
Dunno. I copied the tests and made the command and response both be structs. Not sure what anyone would do that, but now it works;)

**Comment by CodingGorilla** [comment]
@jeremydmiller It looks like this made it back into the 1.0 release?

**Comment by jeremydmiller** [comment]
I don't know why it would have Mark, and there is a test for using structs as messages. If it is, I'm happy to take a PR
