### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/jasper#637]
I've been reading through the docs and Jasper is looking really nice. I have an application that handles millions of requests and puts them immediately into a queue and then I have a separate queue job that processes those requests and scales up and down with demand. How would I go about implementing a service to handle that scenario using Jasper? Thanks in advance!

**Comment by jeremydmiller** [comment]
@ejsmith,

That kind of thing probably doesn't make the 1.0 cut, but my thinking is that you'd rely on particular cloud scale up/down to just start or stop new nodes based on queue depth or CPU load or whatever else. 

I did some work a couple years ago to add metrics collection that's not doing much. If we were doing some kind of Jasper controlled scale up/down, maybe you would use some kind of criteria on that to trigger new nodes.

What were you thinking?

**Comment by ejsmith** [comment]
I guess I'm a bit confused on how to do a traditional single consumer queue. Not seeing any documentation page talking about the difference in conventions between commands, messages and events. I think what I need to do is use the command bus to enqueue messages from the web service, but not register any handlers there. Then I would create a handler job that listens for those commands and scale that up and down based on metrics from RabbitMQ for the current queue size. I need to find some time to play around and test things out. Am I on the right track though?

**Comment by jeremydmiller** [comment]
I think you might be overcomplicating things or bringing in some prior ideas of how something like this works. Jasper doesn't make any distinction structurally between messages, events, and commands. That's really just about what role they play within your system.

If you're just wanting to send messages to an external service via Rabbit MQ or Azure Service Bus, check out the topics here: http://jasperfx.github.io/documentation/integration/.

You'd just have a different application receiving messages as a .Net Core 3.0 worker. How that worker service is deployed or spun up according to the current queue size isn't something I think you absolutely have to have in Jasper itself. Shouldn't you be able to use something like Service Fabric in Azure to scale up or down based on queue depth? It's literally just starting and stopping new instances of a Jasper application. 

I have no intention of going into a real Actor framework like Akka.net that tries to do all that w/ software.

**Comment by jeremydmiller** [comment]
I can definitely add a sample of an ASP.Net Core web service publishing messages to a separate worker process

**Comment by ejsmith** [comment]
I guess I am not getting how you make different message types behave differently like one message type being pub/sub another message type being a worker queue with single consumer with completion acknowledgments, etc.

A sample showing separated publish and worker would be very helpful.

**Comment by jeremydmiller** [comment]
Completely different semantic methods on `ICommandBus` / `IMessagePublisher` / `IMessageContext`. You *can* set up publishing rules to send a message locally, but I think mostly you'd use the explicit command to `Enqueue()` versus `Send()` or `Publish()`. Request/Response and the later acknowledgement workflow are through different methods as well. My thought is that you don't want to have too much magic going on about what Jasper is doing with your message. And to this point, even though it has some routing rules, I mostly want to lean on what tools like Rabbit do for routing anyway.

Does that answer your question? But a sample is a no brainer regardless.

I haven't played the story yet, but I'm adding an acknowledgement workflow based on something we built for a client.

**Comment by ejsmith** [comment]
Ok, so it's the different methods for publishing and consuming that control those things. I see. I think that gets me going. I will find some time to experiment and dig deeper to see if it can meet my needs.
