### ISSUE TITLE
Stateful Saga question

### ISSUE THREAD

**Issue by ShaneCourtrille** [JasperFx/jasper#639]
Is it possible for the state to be a property of the saga itself rather than having to pass it in and modify it each time?  This just cleans up the method a bit and makes it so we don't have to constantly pass state around.

**Comment by jeremydmiller** [comment]
Yeah, I think I like that. I'll pull that into 1.0 since that would be a breaking change.

**Comment by jeremydmiller** [comment]
This is actually done!
