### ISSUE TITLE
Saga questions

### ISSUE THREAD

**Issue by ShaneCourtrille** [JasperFx/jasper#643]
1) if you use context.Send() within a Saga what happens if your saga state persistence fails?  Are the messages still sent?  I don't see mention of this in the documentation

2) Are there any plans to allow Sagas to receive Pub/Sub messages?

**Comment by jeremydmiller** [comment]
So,

1.) Nope, all or nothing. But I can add that to the docs. It's using the "outbox" support.
2.) The commands can come either locally through the `ICommandBus` or originate as external messages through one of the external transports or any mix of the two.

I'm going to take this as documentation things here.

**Comment by jeremydmiller** [comment]
Accidentally closed, so I'm re-opening
