### ISSUE TITLE
Replace all Storyteller Specs

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#685]
#sadtrombone.

*Somebody* is no longer supporting Storyteller, and those tests need to be accounted for somewhere, somehow

**Comment by JarrodJ83** [comment]
Sad trombone indeed! I suspect we'll see a blog post on this soon?

**Comment by jeremydmiller** [comment]
Ugh, it's a longer conversation someday. I just don't have bandwidth right now to reboot storyteller, but I'm iffy on SpecFlow and unhappy w/ xUnit.Net or NUnit as integration testing tools. So dunno.

**Comment by JarrodJ83** [comment]
Fair enough! And for what its worth I agree with you. Seems there is a gap to be filled there.

**Comment by jeremydmiller** [comment]
This was a waste of time. I got some things moved over, but ST is still vastly better than xunit for data intensive tests and the Rider + xUnit runner just chokes on multi-threading, so some ST specs are sticking around for now.
