### ISSUE TITLE
Timeline to update to NET5/6

### ISSUE THREAD

**Issue by aszalacinski** [JasperFx/jasper#694]
Any timeline of when NET5/6 compatibility will make it into master? I see Lamar is getting the updates and knowing that Jasper is dependent on Lamar, wondering if Jasper updates are close. Thanks!

**Comment by jeremydmiller** [comment]
Sorry for the delay. Marten v5 has taken all my spare OSS time for the past couple months. I just barely started to work on Jasper again today. I'll update this issue when I know the answer myself.

**Comment by jeremydmiller** [comment]
By the end of April. Hopefully more like mid-April, but we'll see.
