### ISSUE TITLE
Revamped Jasper Roadmap

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/jasper#92]
I've been thinking about the future of Jasper the past couple weeks, and I actually think I'd like to see us reorganize the codebase and change direction just a little bit. 

The big changes I wanna make:

* Give up on StructureMap usage and just use the built in the ASPNetCore DI container. The Jasper usage so far is vastly simpler than FubuMVC's was, and the built in container is actually faster than SM anyway
* Consolidate the basic features into the single "Jasper" library ala FubuMVC 3.*. I think this simplifies a lot of the bootstrapping code and eliminates some of the bootstrapping permutation problems. Also hoping that this would make the library easier to adopt
* Re-wire the Jasper.Diagnostics functionality to use the JasperHTTP pieces
* *Possibly* add a WebSockets transport to the service bus -- would have made the Storyteller client quicker to build.
* Add a dedicated HTTP transport directly into the main lib & service bus. Would potentially use the JasperHTTP services 

## Topology Today

1. **Jasper** -- base library with the code generation, StructureMap to ASPNetCore DI abstraction, bootstrapping, and the beginnings of the extension (Bottles) 
1. **JasperBus** -- the service bus feature from what was FubuTransportation. Also includes the LQ integration
1. **JasperHTTP** -- Jeremy's vanity project for exposing HTTP services. 
1. **JasperServer** -- experimental project to create "hybrid" ASP.Net Core + JasperBus applications or JasperHTTP + JasperBus
1. **Jasper.Diagnostics** -- both an add on to ASP.Net Core + Jasper applications or a standalone addon to JasperBus applications
1. **JasperBus.Marten** -- Marten backed subscription storage

## Proposed Topology

1. **Jasper** -- base library with the codegen, bootstrapping, HTTP features, the diagnostics, and *basic* service bus functionality. Leave out any persistent subscription or delayed job features to keep the dependency tree lighter. So add JasperHTTP, Jasper.Diagnostics, and most of JasperBus to the main lib
1. **Jasper.LightweightTransport** (???) -- pull in LightningQueues and its bus transport. We're gonna have to get away from LQ in the long run anyway. Might consider keeping strictly the non persistent mode of LQ inside of Jasper itself
1. **Jasper.AMPQ** -- A RabbitMQ/AMPQ transport for the service bus. We'll need this sooner or later for the docker era
1. **Jasper.Marten** -- the Marten backed subscription storage, basic Marten integration, and some transactional middleware & codegen support
1. **Jasper.Consul** -- Consul backed subscription storage? I think there are built in libraries to tie
    Consul into the new ASPNetCore Configuration as is
1. **Jasper.Hangfire** -- opts into a persistent job scheduler for the delayed job feature in the service bus
1. **Jasper.Storyteller** -- Recipe for integrating Jasper applications into a Storyteller spec project. Pull over the Storyteller diagnostics integration we had in FubuMVC w/ Serenity
1. **JasperHost** -- we really need some kind of TopShelf-like recipe for hosting Jasper apps in windows services

**Comment by ejsmith** [comment]
Just reading through the issues @jeremydmiller. I like this plan. Seems to simplify things substantially.

One question: any particular reason you want to use Consul over etcd? Reason I ask is because etcd is used by Kubernetes and I've seen a few blog posts showing etcd performing and behaving a lot better than Consul. Just curious.

**Comment by joemcbride** [comment]
Just adding my 👍  - I like the consolidating of projects and am interested in seeing where the JasperHTTP/JasperServer portion goes.

**Comment by jeremydmiller** [comment]
@ejsmith I really don't have any experience with either, but our DevOps team is already using Consul with the intention of that being used for Docker. Good question to bring up some day;)

**Comment by jeremydmiller** [comment]
*Most* of the proposed consolidation got done, and I split out separate issues for most of the bullet points here. For now, I'm voting to keep the diagnostics separate, but some of that is from the #107 extension
